### ISSUE TITLE
reviewing responsive page projcet milestone 2

### ISSUE THREAD

**Issue by igorkol91** [blakbox23/tnw-news#3]

**Comment by igorkol91** [comment]
it looks great I'm sure you will get approved this time

**Comment by SamanAtashi** [comment]
it looks great man , Keep on going.

**Comment by ahzia** [comment]
@SamanAtashi @igorkol91, Thanks for the review!

**Comment by vikitaotiz** [comment]
Keep up the good work... I see no issues...
